### ISSUE TITLE
Integrate Roboelectric for Unit Testing Support and Integration testing on Travis CI

### ISSUE THREAD

**Issue by laurawheatley** [aa-software2112/SOEN390_SimpleCamera#13]
Choose an emulator (device) and have it run in Travis through the command line (see this link for more details --> https://github.com/aa-software2112/SOEN390_SimpleCamera/wiki/Testing-Environment); the emulator should send some command to the application and have a detectable response.

- [x] Add example using main view 
- [x] w/ Mockito if possible
- [x] Make sure it works on Travis (robolectric tests are executed and pass)

Source Story: #5
[Story points: 1]
[Ideal hours: 2]

**Comment by aa-software2112** [comment]
So far this issue has been a royal pain; i have removed @samgo1 old travis code just to be able to download and install the emulator itself without building the application (which takes several minutes and I would not be able to finish this within any reasonable time). Once the emulator is working, I will put his code back.

@Lussier115 I would recommend holding off on touching this until I have the emulator installed, at which point you can look into communicating with it (I will let you know when it is done).

So far the progress is:
1. Install all necessary android tools (/tools, /platform-tools (for adb), /emulator (for emulator command line), and /system-images (from google_apis - this is a large file and adds roughly a minute or so to the entire build process...)
2. Android 28 sdk installs
3. An emulator called travisEmulator is created (but not started)

Here is what is left to implement before handing it off to @Lussier115 
4. Start the emulator

then @Lussier115 will send some input to the application using adb

**Comment by aa-software2112** [comment]
New development:
The current Travis build successfully launches an emulator and loads the application onto it after it is built;
at the end of the current travis script, there is an emulator running ready to accept commands. After reading further into the matter, the best way to perform acceptance tests is as follows;
1. Run emulator (done)
2. Build APK (application) (done)
3. Load built APK onto emulator (done)
4. Write & Load instrumentation test APK onto emulator (http://mattsnider.com/running-android-tests-on-a-device-or-emulator/) (NOT done)

@Lussier115 the last part we need is to write a basic instrumentation test (In Espresso) that will be loaded onto the emulator. Note that an instrumentation test is one that allows for navigation of the application through java/kotlin but instead of unit tests (which run on the Java JVM), it will run on the emulator (which simulates the hardware). The best way to set up the instrumentation tests without using Travis (so that you can get it to work locally before wasting your time with 10-minute travis builds) is as follows.
1. Run Android Studio
2. Run an emulator through Android Studio (a physical one)
3. Open a command window and use the current Travis.yml script as inspiration for loading the application (APK) onto the emulator (you may have to use this link to see which emulator devices are opened, and connect to it (the one open in android studio) http://mattsnider.com/running-android-tests-on-a-device-or-emulator/)
4. Write an instrumentation test, and load it's APK into the emulator from the command line. If you can get this to work, we can add this script into Travis to complete our job. I know this may be slightly confusing so feel free to give me a call 514-443-5211 and i'll talk you through this! Also don't forget youtube and google!

**Comment by aa-software2112** [comment]
Link w/ useful background to instrumentation tests https://stuff.mit.edu/afs/sipb/project/android/docs/tools/testing/testing_android.html

**Comment by aa-software2112** [comment]
It was decided that the choice of acceptance testing via the emulator is unnecessary (TA confirmed that it can simply be a table listing all acceptance tests for the entire release (and sprint), and whether or not they passed). This issue will be modified to reflect these changes
